/// 365 frases de motivación sobre emprendimiento, negocios, espiritualidad y psicología.
/// Una frase para cada día del año.
const List<String> frasesMotivacionalesDiarias = [
  // Frase especial de inicio
  'No olvido el color de tu mirada.',

  // Emprendimiento y Negocios (60 frases)
  'El éxito es la suma de pequeños esfuerzos repetidos día tras día.',
  'No esperes el momento perfecto, toma el momento y hazlo perfecto.',
  'Tu único límite es tu propia mentalidad.',
  'El fracaso es solo la oportunidad de comenzar de nuevo con más inteligencia.',
  'El dinero es una consecuencia, no un objetivo.',
  'La mejor inversión que puedes hacer es en ti mismo.',
  'No cuentes los días, haz que los días cuenten.',
  'El éxito no es casualidad, es trabajo duro, perseverancia y aprendizaje.',
  'Quien no arriesga, no gana.',
  'La disciplina es el puente entre metas y logros.',
  'Tu tiempo es limitado, no lo desperdicies viviendo la vida de otra persona.',
  'La única forma de hacer un gran trabajo es amar lo que haces.',
  'El que no vive para servir, no sirve para vivir.',
  'No dejes para mañana lo que puedes hacer hoy.',
  'El éxito es aprender a ir de fracaso en fracaso sin desesperarse.',
  'La motivación es lo que te pone en marcha, el hábito es lo que te mantiene.',
  'No busques clientes para tus productos, busca productos para tus clientes.',
  'El cliente no siempre tiene la razón, pero siempre es el cliente.',
  'Vende valor, no precio.',
  'La mejor publicidad es un cliente satisfecho.',
  'No vendas lo que produces, produce lo que se vende.',
  'El marketing es contar tu historia de forma que la gente se enamore de tu solución.',
  'La marca más poderosa es la que vive en la mente del consumidor.',
  'El precio es lo que pagas, el valor es lo que recibes.',
  'Un negocio sin datos es como conducir con los ojos cerrados.',
  'La innovación distingue a los líderes de los seguidores.',
  'No tengas miedo de renunciar a lo bueno para ir a por lo grandioso.',
  'El mejor momento para plantar un árbol fue hace 20 años. El segundo mejor momento es ahora.',
  'La única estrategia perdedora es no arriesgarse.',
  'El fracaso es simplemente la oportunidad para empezar de nuevo de forma más inteligente.',
  'Si no estás dispuesto a arriesgar lo inusual, tendrás que conformarte con lo ordinario.',
  'El éxito no es la llave de la felicidad. La felicidad es la llave del éxito.',
  'La diferencia entre quien eres y quien quieres ser es lo que haces.',
  'No cuentes los problemas, cuenta las soluciones.',
  'El talento gana partidos, pero el trabajo en equipo gana campeonatos.',
  'La única persona a la que estás destinado a convertirte es la persona que decidas ser.',
  'No te compares con otros. Compárate con quien eras ayer.',
  'El éxito consiste en ir de fracaso en fracaso sin perder el entusiasmo.',
  'La calidad nunca es un accidente; siempre es el resultado del esfuerzo inteligente.',
  'El buen servicio al cliente cuesta menos que la publicidad.',
  'No tengas miedo de renunciar a lo bueno para ir tras lo excelente.',
  'La satisfacción del cliente es nuestra mejor estrategia de marketing.',
  'El que quiere hacer algo encuentra un medio, el que no, encuentra una excusa.',
  'La visión sin acción es un sueño. La acción sin visión es una pesadilla.',
  'No puedes construir una reputación sobre lo que vas a hacer.',
  'El secreto de avanzar es comenzar.',
  'Las grandes cosas nunca vienen de las zonas de confort.',
  'El único modo de hacer un gran trabajo es amar lo que haces.',
  'El emprendedor ve oportunidades donde otros ven obstáculos.',
  'No se trata de tener tiempo, se trata de hacer tiempo.',
  'El éxito es la capacidad de ir de fracaso en fracaso sin perder entusiasmo.',
  'La persistencia es el camino del éxito.',
  'Tu red de contactos es tu patrimonio neto.',
  'El conocimiento sin acción es inútil.',
  'La mejor venganza es el éxito masivo.',
  'No dejes que el miedo al fracaso te impida jugar el juego.',
  'El que no se arriesga no cruza el río.',
  'La suerte es lo que sucede cuando la preparación se encuentra con la oportunidad.',
  'El único lugar donde el éxito viene antes que el trabajo es en el diccionario.',
  'No importa cuán lento vayas siempre y cuando no te detengas.',

  // Espiritualidad (60 frases)
  'Lo que niegas te somete, lo que aceptas te transforma.',
  'El momento presente es todo lo que tienes.',
  'La paz viene de dentro, no la busques fuera.',
  'Eres lo que piensas, no lo que piensas que eres.',
  'La felicidad no es algo hecho. Viene de tus propias acciones.',
  'El sufrimiento es opcional, el dolor es inevitable.',
  'Donde hay amor, hay vida.',
  'La gratitud convierte lo que tenemos en suficiente.',
  'No eres una gota en el océano, eres el océano entero en una gota.',
  'El silencio es la respuesta más poderosa.',
  'La felicidad es interior, no exterior.',
  'Sé el cambio que quieres ver en el mundo.',
  'El universo conspira a tu favor.',
  'Todo lo que buscas también te está buscando a ti.',
  'La vida es un eco: lo que envías, regresa.',
  'El amor es la energía más poderosa del universo.',
  'Medita, vibra alto, manifiesta.',
  'Tu vibración atrae tu tribu.',
  'La abundancia es un estado mental.',
  'Confía en el proceso, confía en el universo.',
  'Lo que resistes, persiste. Lo que aceptas, se transforma.',
  'El ego dice: cuando todo esté bien, encontraré la paz. El espíritu dice: encuentra la paz y todo estará bien.',
  'No eres tus pensamientos, eres quien los observa.',
  'El presente es el único momento que realmente existe.',
  'La meditación es el arte de no hacer nada y dejar que las cosas sucedan.',
  'El amor propio es el principio de una vida entera de amor.',
  'Tu energía introduce más que tus palabras.',
  'La vida fluye cuando tú fluyes.',
  'Suelta lo que no puedes controlar.',
  'El perdón libera al prisionero, y descubres que el prisionero eras tú.',
  'Todo tiene su tiempo, confía.',
  'Las coincidencias son mensajes del universo.',
  'Eres un ser espiritual viviendo una experiencia humana.',
  'La luz que buscas está dentro de ti.',
  'El milagro no es caminar sobre el agua, es caminar sobre la tierra.',
  'Respira, suelta, confía.',
  'El universo nunca te da más de lo que puedes manejar.',
  'La intuición es el lenguaje del alma.',
  'Cuando caminas en tu verdad, el universo te respalda.',
  'La energía que das es la energía que recibes.',
  'Alinearse es la clave.',
  'Tu frecuencia determina tu realidad.',
  'Ama sin condiciones, vive sin miedo.',
  'El propósito del alma es evolucionar.',
  'La vida es un espejo de tu estado interior.',
  'Honra tu camino, respeta el de los demás.',
  'El despertar espiritual es un proceso, no un destino.',
  'La rendición no es debilidad, es sabiduría.',
  'Confía en la magia de los nuevos comienzos.',
  'Donde está tu atención, está tu energía.',
  'El silencio es donde se encuentran las respuestas.',
  'La espiritualidad es vivir en consciencia.',
  'El amor es la respuesta a cualquier pregunta.',
  'Conecta con tu esencia, no con tu ego.',
  'La paz interior es el nuevo éxito.',
  'El universo tiene un plan mejor que el tuyo.',
  'Fluye con la vida, no contra ella.',
  'La luz vence siempre a la oscuridad.',
  'Tu alma sabe el camino.',
  'Vive en el ahora, es lo único real.',
  'La compasión es la mayor forma de amor.',

  // Psicología y Desarrollo Personal (80 frases)
  'La mente es como un paracaídas, solo funciona si se abre.',
  'No puedes controlar lo que pasa, pero sí cómo reaccionas.',
  'Tus creencias determinan tu realidad.',
  'El cambio empieza en tu mente.',
  'La ansiedad es el precio de vivir en el futuro.',
  'La depresión es el precio de vivir en el pasado.',
  'Lo que te enoja, te controla.',
  'La felicidad es una elección, no una consecuencia.',
  'Tus pensamientos crean tu realidad.',
  'La autoaceptación es el primer paso hacia el crecimiento.',
  'No eres tus errores, eres tu capacidad de aprender de ellos.',
  'La vulnerabilidad es la cuna de la innovación y la creatividad.',
  'El autoconocimiento es el principio de la sabiduría.',
  'Tu zona de confort es el lugar donde mueren los sueños.',
  'La resiliencia no es evitar el dolor, es atravesarlo.',
  'El miedo es temporal, el arrepentimiento es permanente.',
  'La comparación es el ladrón de la alegría.',
  'Tu diálogo interno determina tu vida externa.',
  'Los límites saludables son amor propio en acción.',
  'No puedes sanar en el mismo ambiente donde enfermaste.',
  'El autoperdón es el regalo más grande que puedes darte.',
  'La inteligencia emocional es más importante que el coeficiente intelectual.',
  'Tus hábitos determinan tu destino.',
  'El pensamiento positivo no lo es todo, pero lo cambia todo.',
  'No eres lo que te pasó, eres lo que decides ser.',
  'La procrastinación es miedo disfrazado de pereza.',
  'El perfeccionismo es la forma más alta del auto-sabotaje.',
  'Tu valor no disminuye por la incapacidad de alguien de ver tu valía.',
  'El estrés es causado por estar aquí pero querer estar allí.',
  'La madurez emocional es saber cuándo hablar y cuándo callar.',
  'No puedes verter de una taza vacía, cuídate primero.',
  'El inconsciente es más sabio que el consciente.',
  'Los traumas no sanados se repiten.',
  'Lo que niegas en ti mismo te lo encontrarás en otros.',
  'El duelo es amor sin lugar a donde ir.',
  'El ego es el enemigo del crecimiento.',
  'La proyección psicológica revela más del que proyecta que del proyectado.',
  'El niño interior herido dirige al adulto inconsciente.',
  'La ansiedad es el cuerpo diciendo: estás viviendo muy rápido.',
  'La depresión es el cuerpo diciendo: necesitas un descanso profundo.',
  'No hay emociones negativas, solo emociones mal gestionadas.',
  'El autoconocimiento es el antídoto contra el sufrimiento.',
  'Los patrones se repiten hasta que se aprende la lección.',
  'La salud mental no es un destino, es un proceso.',
  'El autocuidado no es egoísmo, es supervivencia.',
  'La gratitud reprograma el cerebro.',
  'La neuroplasticidad prueba que el cambio siempre es posible.',
  'El mindfulness es la práctica de estar presente.',
  'La coherencia entre pensar, sentir y actuar genera paz.',
  'El síndrome del impostor desaparece cuando actúas a pesar del miedo.',
  'La validación externa es adictiva, la interna es libertad.',
  'El apego es sufrimiento, el desapego es paz.',
  'La codependencia es amarse menos para que otro te ame más.',
  'Los límites enseñan a los demás cómo tratarte.',
  'No puedes cambiar a nadie, solo inspirar con tu ejemplo.',
  'El comportamiento es comunicación.',
  'Detrás de cada crítica hay una necesidad no satisfecha.',
  'La empatía construye puentes, el juicio los destruye.',
  'El perdón no cambia el pasado, pero libera el futuro.',
  'La culpa mira al pasado, la responsabilidad mira al futuro.',
  'El autocrítico interno es el eco de voces externas del pasado.',
  'La asertividad es respetarte a ti mismo mientras respetas a otros.',
  'La soledad es cuando estás solo, el sentirse solo es cuando estás desconectado de ti.',
  'El miedo al éxito es tan real como el miedo al fracaso.',
  'La autoestima no se construye con elogios, se construye con logros.',
  'La coherencia emocional es alinear lo que piensas, sientes y haces.',
  'La zona de crecimiento empieza donde termina la zona de confort.',
  'El victimismo te quita poder, la responsabilidad te lo devuelve.',
  'La sombra psicológica contiene tanto oro como basura.',
  'Integrar la sombra es aceptar tu humanidad completa.',
  'El ego tiene miedo de morir, el alma sabe que es inmortal.',
  'La ansiedad anticipatoria es sufrir dos veces.',
  'El rumiamiento mental es la prisión del pensamiento.',
  'La regulación emocional es una habilidad, no un talento innato.',
  'El trauma no es lo que te pasó, es lo que quedó sin resolver en ti.',
  'La desregulación emocional es una señal, no un defecto.',
  'El autoconocimiento ilumina, la negación oscurece.',
  'La congruencia entre valores y acciones genera integridad.',
  'El cambio duele, pero quedarse donde no perteneces duele más.',
  'La resistencia al cambio es normal, quedarse estancado es opcional.',
  'La neurociencia confirma: nunca es tarde para cambiar.',

  // Frases adicionales - Emprendimiento y Negocios (55 frases)
  'El emprendedor no es quien tiene las mejores ideas, sino quien las ejecuta.',
  'La competencia es para los mediocres, los genios crean categorías.',
  'Un buen plan hoy es mejor que un plan perfecto mañana.',
  'La escalabilidad es la diferencia entre un negocio y un trabajo.',
  'El cash flow es más importante que el beneficio.',
  'La velocidad de implementación es una ventaja competitiva.',
  'No construyas un producto, construye un negocio.',
  'La diferenciación es más importante que la perfección.',
  'El pivotaje es inteligencia, no fracaso.',
  'Tu competencia no es tu enemigo, es tu maestro.',
  'El producto mínimo viable es el inicio, no el final.',
  'La iteración constante supera a la planificación perfecta.',
  'El mercado siempre tiene la razón.',
  'Valida antes de construir, construye antes de escalar.',
  'La tracción habla más fuerte que las ideas.',
  'Un cliente real vale más que cien potenciales.',
  'El feedback negativo es oro puro disfrazado.',
  'La automatización libera tiempo para pensar.',
  'Los sistemas trabajan para ti, los empleos trabajan contra ti.',
  'El branding es lo que dicen de ti cuando no estás presente.',
  'La credibilidad se construye promesa a promesa cumplida.',
  'El boca a boca es el santo grial del marketing.',
  'Un nicho profundo vale más que un mercado superficial.',
  'La especialización es la clave de la monetización.',
  'El posicionamiento correcto vale más que mil anuncios.',
  'La prueba social es más poderosa que cualquier argumento de venta.',
  'El storytelling vende más que las características.',
  'La escasez genuina crea urgencia, la artificial crea desconfianza.',
  'La reciprocidad es el primer principio de influencia.',
  'El compromiso público aumenta la probabilidad de acción.',
  'La autoridad se construye compartiendo conocimiento.',
  'La consistencia es más persuasiva que la intensidad.',
  'El contraste magnifica el valor percibido.',
  'El precio ancla determina la percepción de valor.',
  'La garantía elimina el riesgo y aumenta la conversión.',
  'El upsell es donde está la verdadera ganancia.',
  'La retención de clientes es más rentable que la adquisición.',
  'El lifetime value es la métrica que importa.',
  'Un funnel optimizado vale más que mil visitas.',
  'La segmentación precisa multiplica el ROI.',
  'El copywriting persuasivo convierte mejor que el diseño bonito.',
  'Los testimonios específicos convierten mejor que los genéricos.',
  'El lead magnet debe resolver un problema específico.',
  'La secuencia de emails es donde sucede la relación.',
  'El contenido de valor atrae, el contenido promocional repele.',
  'La educación vende mejor que la persuasión.',
  'El email marketing tiene el mejor ROI de todos los canales.',
  'La lista de correo es tu activo más valioso.',
  'El SEO es una maratón, no un sprint.',
  'El contenido perenne es el regalo que sigue dando.',
  'Las palabras clave long-tail convierten mejor.',
  'El link building de calidad supera la cantidad.',
  'La experiencia de usuario es el nuevo SEO.',
  'La velocidad del sitio afecta tanto al SEO como a las conversiones.',
  'El mobile-first no es opcional, es obligatorio.',
  'La prueba A/B constante es la única forma de mejorar.',

  // Frases adicionales - Espiritualidad (55 frases)
  'El despertar es recordar quién eras antes de que el mundo te dijera quién deberías ser.',
  'La vida no te pasa a ti, te pasa por ti.',
  'Eres el cielo, todo lo demás es solo el clima.',
  'La rendición no es darte por vencido, es confiar.',
  'El ego busca validación, el alma busca expresión.',
  'Tu tarea no es buscar el amor, sino derribar las barreras que construiste contra él.',
  'La iluminación es el espacio entre dos pensamientos.',
  'No hay camino hacia la paz, la paz es el camino.',
  'El sufrimiento termina cuando la resistencia termina.',
  'Tu verdadero yo está más allá de tus pensamientos y emociones.',
  'La separación es una ilusión, la unidad es la verdad.',
  'El tiempo no existe, solo existe el ahora eterno.',
  'La mente juzga, el corazón comprende, el alma sabe.',
  'El observador no puede ser lo observado.',
  'La consciencia es el testigo silencioso de toda experiencia.',
  'El sufrimiento nace del deseo de que las cosas sean diferentes.',
  'La aceptación radical es la puerta a la paz.',
  'No eres el personaje de tu historia, eres el autor.',
  'El despertar espiritual no te hace mejor que otros, te hace consciente.',
  'La luz no lucha contra la oscuridad, simplemente brilla.',
  'El alma habla en susurros, el ego grita.',
  'La verdad no necesita defensa, se sostiene por sí misma.',
  'El camino espiritual es desaprender, no aprender.',
  'Lo sagrado está en lo ordinario.',
  'La vida es el gurú, la experiencia es la enseñanza.',
  'El karma no es castigo, es balance.',
  'Lo que das, recibes. Lo que siembras, cosechas.',
  'El universo no castiga ni premia, refleja.',
  'Cada encuentro es una cita divina.',
  'Las sincronicidades son guiños del universo.',
  'Tu vibración es tu firma energética.',
  'La energía no miente, aunque las palabras sí.',
  'El aura habla antes que la boca.',
  'Los chakras son los portales del alma.',
  'La respiración conecta cuerpo, mente y espíritu.',
  'La presencia es el mayor regalo que puedes dar.',
  'El silencio interior es más elocuente que mil palabras.',
  'La meditación no es ausencia de pensamiento, es presencia en el ser.',
  'El yoga une, no separa.',
  'El prana es la fuerza vital que todo lo anima.',
  'La energía Kundalini es el poder latente del alma.',
  'El tercer ojo ve lo invisible.',
  'La intuición es la voz del alma hablando.',
  'Los sueños son mensajes del subconsciente.',
  'El simbolismo oculto revela verdades universales.',
  'La luna gobierna las emociones, el sol gobierna la acción.',
  'Cada estación es una metáfora de transformación.',
  'La naturaleza es la maestra más sabia.',
  'Los elementos (fuego, agua, tierra, aire) viven en ti.',
  'El amor incondicional es la frecuencia más alta.',
  'El servicio desinteresado purifica el alma.',
  'La compasión es ver tu propia humanidad en el otro.',
  'El desapego no es indiferencia, es libertad.',
  'La gratitud eleva tu vibración instantáneamente.',
  'La bendición silenciosa transforma energías.',
  'La oración es hablar con Dios, la meditación es escuchar.',

  // Frases adicionales - Psicología y Desarrollo Personal (55 frases)
  'El cerebro no distingue entre realidad e imaginación vívidamente experimentada.',
  'La repetición crea nuevas rutas neuronales.',
  'El estrés crónico encoge el hipocampo y daña la memoria.',
  'La amígdala reacciona antes que la corteza prefrontal.',
  'El cerebro reptiliano busca supervivencia, el neocórtex busca significado.',
  'La dopamina motiva, la serotonina satisface, la oxitocina conecta.',
  'El cortisol elevado bloquea la lógica y activa el instinto.',
  'Dormir bien es más importante para la salud mental que cualquier terapia.',
  'El ejercicio físico es el antidepresivo más potente y natural.',
  'La alimentación afecta el estado de ánimo más de lo que imaginas.',
  'El microbioma intestinal influye directamente en tu salud mental.',
  'La luz solar regula el ritmo circadiano y el estado de ánimo.',
  'El contacto social es una necesidad biológica, no un lujo.',
  'El aislamiento social activa las mismas áreas cerebrales que el dolor físico.',
  'La risa libera endorfinas y reduce el cortisol.',
  'El llanto es una forma de regulación emocional, no debilidad.',
  'La escritura expresiva reduce la ansiedad y mejora el estado de ánimo.',
  'El arte terapéutico accede al subconsciente mejor que las palabras.',
  'La música modifica el estado emocional en tiempo real.',
  'El movimiento corporal libera emociones atrapadas.',
  'El contact físico libera oxitocina, la hormona del vínculo.',
  'El abrazo de 20 segundos reduce significativamente el estrés.',
  'La respiración profunda activa el sistema nervioso parasimpático.',
  'La técnica 4-7-8 calma la ansiedad en minutos.',
  'El box breathing es usado por militares para manejar estrés extremo.',
  'La visualización positiva prepara el cerebro para el éxito.',
  'Las afirmaciones reprograman el diálogo interno negativo.',
  'El efecto Pigmalión demuestra que las expectativas crean realidades.',
  'El efecto placebo prueba el poder de la creencia.',
  'La profecía autocumplida es real y poderosa.',
  'El sesgo de confirmación refuerza tus creencias existentes.',
  'La disonancia cognitiva causa incomodidad psicológica.',
  'El efecto halo hace que una cualidad positiva influya en la percepción total.',
  'La fatiga de decisión agota tu fuerza de voluntad.',
  'El autocontrol es un recurso limitado que se agota.',
  'Los hábitos atómicos crean cambios exponenciales.',
  'La regla de los 21 días es un mito, formar hábitos toma en promedio 66 días.',
  'El encadenamiento de hábitos facilita la integración de nuevas conductas.',
  'La identidad basada en hábitos es más poderosa que los objetivos.',
  'El ambiente diseñado inteligentemente reduce la necesidad de fuerza de voluntad.',
  'La arquitectura de elección determina tus decisiones automáticas.',
  'Los disparadores ambientales activan conductas automáticas.',
  'La recompensa inmediata es más motivadora que la futura.',
  'El refuerzo positivo funciona mejor que el castigo.',
  'La gamificación aprovecha los sistemas de recompensa del cerebro.',
  'El progreso visible mantiene la motivación alta.',
  'El efecto Zeigarnik hace que las tareas incompletas ocupen la mente.',
  'El principio de Pareto: el 20% del esfuerzo produce el 80% de los resultados.',
  'La ley de Parkinson: el trabajo se expande hasta llenar el tiempo disponible.',
  'El timeboxing aumenta la productividad y reduce la procrastinación.',
  'La técnica Pomodoro aprovecha la atención limitada del cerebro.',
  'El trabajo profundo (deep work) crea valor exponencial.',
  'La multitarea es un mito, el cerebro cambia rápidamente entre tareas.',
  'El costo de cambio de contexto reduce la productividad hasta un 40%.',
  'La regla de los dos minutos: si toma menos de dos minutos, hazlo ahora.',
  'El principio de comer la rana: empieza por la tarea más difícil.',
];
